//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.03 at 03:33:41 PM CEST 
//


package it.joshua.crobots.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.joshua.crobots.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Tie_QNAME = new QName("", "Tie");
    private final static QName _Win_QNAME = new QName("", "Win");
    private final static QName _Games_QNAME = new QName("", "Games");
    private final static QName _Points_QNAME = new QName("", "Points");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.joshua.crobots.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Match }
     * 
     */
    public Match createMatch() {
        return new Match();
    }

    /**
     * Create an instance of {@link Robot }
     * 
     */
    public Robot createRobot() {
        return new Robot();
    }

    /**
     * Create an instance of {@link Robots }
     * 
     */
    public Robots createRobots() {
        return new Robots();
    }

    /**
     * Create an instance of {@link MatchList }
     * 
     */
    public MatchList createMatchList() {
        return new MatchList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tie")
    public JAXBElement<Integer> createTie(Integer value) {
        return new JAXBElement<Integer>(_Tie_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Win")
    public JAXBElement<Integer> createWin(Integer value) {
        return new JAXBElement<Integer>(_Win_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Games")
    public JAXBElement<Integer> createGames(Integer value) {
        return new JAXBElement<Integer>(_Games_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Points")
    public JAXBElement<Integer> createPoints(Integer value) {
        return new JAXBElement<Integer>(_Points_QNAME, Integer.class, null, value);
    }

}
