//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.03 at 03:33:41 PM CEST 
//


package it.joshua.crobots.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Win"/>
 *         &lt;element ref="{}Tie"/>
 *         &lt;element ref="{}Points"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "win",
    "tie",
    "points"
})
@XmlRootElement(name = "Robot")
public class Robot {

    @XmlElement(name = "Win")
    protected int win;
    @XmlElement(name = "Tie")
    protected int tie;
    @XmlElement(name = "Points")
    protected int points;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the win property.
     * 
     */
    public int getWin() {
        return win;
    }

    /**
     * Sets the value of the win property.
     * 
     */
    public void setWin(int value) {
        this.win = value;
    }

    /**
     * Gets the value of the tie property.
     * 
     */
    public int getTie() {
        return tie;
    }

    /**
     * Sets the value of the tie property.
     * 
     */
    public void setTie(int value) {
        this.tie = value;
    }

    /**
     * Gets the value of the points property.
     * 
     */
    public int getPoints() {
        return points;
    }

    /**
     * Sets the value of the points property.
     * 
     */
    public void setPoints(int value) {
        this.points = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
